### ISSUE TITLE
panic: runtime error: index out of range [10] with length 10[BUG]

### ISSUE THREAD

**Issue by bcheevers123** [ThrillQuks/Pitraix#14]
**What operating system are you using? (exact version)**
- Kali Linux

**What operating system is the host running? (exact version)**
- Kali Linux / Windows 10

**Are you using Release or master?**
- master

** Did you or the host have TOR previously installed?**
- No

**Are you running both OPER and lyst payload on same machine?**
- Yes and No

**Did you compile OPER and lyst payloads according to the README.md?**
- Yes

**Describe the bug**

I compiled both the lyst_window and lyst_linux payloads using the suggested flags in the README. I ran the OPER.exe, which worked.

I ran the lyst_window.exe on my Windows 10 Virtual Machine (Virtual Box). A console window came up, spat out the RSA key and then died. I ran ls on the OPER and no agent created. Please note that Windows defender and windows firewall were both turned off.

I then tried lyst_linux on my kali linux machine (which is a bare-metal/ non-vm machine) and got a look at the error message
```

panic: runtime error: index out of range [10] with length 10
goroutine 1 [running]:
main.getMachineInfo()
    /home/barry/Desktop/Pitraix-main/pitraix/lyst_linux.go:1146 +0x59c
main.main()
    /home/barry/Desktop/Pitraix-main/pitraix/lyst_linux.go:1231 +0x3b5
```

**To Reproduce**

Step 1: Compile and run OPER

Step 2: Compile linux_lyst using` GOOS=linux go build -ldflags="-s -w " lyst_linux.go` or for windows: `GOOS=windows go build -ldflags="-s -w -H=windowsgui" lyst_windows.go`

Step 3: Run the executable on the corresponding platform.
**Expected behavior**

Agent to be created, and visible from OPER

**Screenshots**

Linux

![image](https://user-images.githubusercontent.com/89908497/186136219-bf9e2de1-5263-4494-afbf-64e4aafacc20.png)

Windows:

![image](https://user-images.githubusercontent.com/89908497/186137132-64b671f2-e0de-45b8-be88-acf32d0274d1.png)

**Additional context**
Seems to suggest issue in getMachineInfo() function

**Comment by GuiltyDescent** [comment]
Try compiling with this command
`GOOS=linux GOARCH=386 go build -ldflags="-s -w " lyst_linux.go`
`GOARCH=386` makes it into a 32-bit program
if that does not work try making sure it's compiled into a 64-bit program with
`GOOS=linux GOARCH=amd64 go build -ldflags="-s -w " lyst_linux.go`

**Comment by ThrillQuks** [comment]
> Try compiling with this command `GOOS=linux GOARCH=386 go build -ldflags="-s -w " lyst_linux.go` `GOARCH=386` makes it into a 32-bit program if that does not work try making sure it's compiled into a 64-bit program with `GOOS=linux GOARCH=amd64 go build -ldflags="-s -w " lyst_linux.go`

please **do not** do that! This is the most counterproductive answer I seen. **do not** compile that way.

For debugging compile examples:
Linux: `GOOS=linux go build lyst_linux.go`
Windows: `GOOS=windows go build lyst_windows.go`

**Comment by GuiltyDescent** [comment]
I apologize, I recognize I did not understand what I was commenting. Please forgive this mistake.

**Comment by bcheevers123** [comment]
> can you please run `hostnamectl` on the linux host and post output?
> 
> as for windows one, you are running in a vm, and anti-vm kicks in and stops execution.

┌──(barry㉿kali)-[~/Desktop/Pitraix-main/pitraix]
└─$ hostnamectl
 Static hostname: kali
       Icon name: computer
      Machine ID: 698427b472d9428986f98cd76b854f89
         Boot ID: e10fa419e0b94a92b5bca43ae00c7100
Operating System: Kali GNU/Linux Rolling
          Kernel: Linux 5.18.0-kali5-amd64
    Architecture: x86-64
 Hardware Vendor: ASUSTeK COMPUTER INC.
  Hardware Model: UX430UAR
Firmware Version: UX430UAR.308

**Comment by bcheevers123** [comment]
> can you please run `hostnamectl` on the linux host and post output?
> 
> as for windows one, you are running in a vm, and anti-vm kicks in and stops execution.
> 
> try latest lyst_windows master as i have temporarily disabled anti-vm code there (can be re-enabled by setting `antiVM_Enabled` to `true`)

Got your latest lyst_windows and lyst_linux.go files and compiled using previously mentioned method. On windows and linux same result

![image](https://user-images.githubusercontent.com/89908497/186484388-7d8cb477-1437-48f3-b460-5f9809e33396.png)

**Comment by ThrillQuks** [comment]
> Got your latest lyst_windows and lyst_linux.go files and compiled using previously mentioned method. On windows and linux same result
> 
> ![image](https://user-images.githubusercontent.com/89908497/186484388-7d8cb477-1437-48f3-b460-5f9809e33396.png)

seems like you did not compile it using this command `GOOS=windows go build lyst_windows.go`

also you don't need to keep printing `ls` since oper will let you know when a new host registers

**Comment by ThrillQuks** [comment]
also when recompiling lyst, be sure to delete files called `OPER_PrivateKey` then run oper for first time and it will embed keys into the executable which might be the problem

**Comment by bcheevers123** [comment]
Hi, so I deleted the OPER Pub and Private keys, then recompiled.

└─$ ./lyst_linux                                                          127 ⨯
addr: -----BEGIN RSA PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAsQ0wVJZvsmodGzHadR0R
PKD6sE/GeCGYh5y0F9kwU4rhtA3CuN1NB71L70nmscJA2MikV9JkW4wKBpKsfR7U
KsoBKx629/u787bTKT7+idqWndp7iI/kTiD5MWuFAfiM+yLnfcHJA6PJdWdT8W7v
pXJF8H++P5NASCjowLlN+kYrzu6HmgyAXp4OF1+uOts2bfRJEwYLaNUn/Mxc+PBJ
/Z5i8VeCChCugPcGvmRVzu9GERaoPN4QUjXWX7LEofu8pLet4Y+/S6Ux2wT+S++/
sYmVGJCzC3lIAQvkB9I2Wb88mJbdbbKRXVrwp2AxuDI/vSLaJXFIDfoXxfdFxtQZ
+SCo4H8lDnGSBmODdkauGOTCwaLdqu4RMTtcq7kN/qNqhlsh6kh4Il88nOCEYUwL
AnKag13ECh6LS1mQIluKu5a8ntqvjPtqDDaIFrOykNDUP0VcKiO3+w0SKcGyJLeH
qhNjWg5fcgHZ1lqXxaajR9gk9Lu8HtsS9wDUgfz2z48hUFcprn80Y5yGStLXEMUc
xFuYrug4ehrVm7IZjkUNRjs4y4TmrNResUx+b7kBBnh5MKxmlNrX1JcIc6I2H7gJ
h/5vKzKDHEAs/yrMS6Vg4ZPMSdGB2XL0QsWD0HS0rExX6Vn38jumrbUYbg21knKo
qKiNK1DrgfKGtDHN8yurYCsCAwEAAQ==
-----END RSA PUBLIC KEY----- pcv7id2nsrzx4zzqgg4gqkmrctv457cyvbe75dbc7wbwdqbv2x4i7mad
Recovered in zsplit:  runtime error: index out of range [10] with length 10
 0   0  
updated cft but not conf file
temporary persisted /home/barry/.local/share/.5nFHfUW1jRASehH3
Tor not found! Downloading..
Found, doing found check..
hostname read error: open /home/barry/.local/share/.5xuWRjOJoYNq2C7eXhEeZdGAJ/.5xuWRjOJoYNq2C7eXhEeZdGAJhid/hostname: no such file or directory
Tor not found! Downloading..
Found, doing found check..
hostname read error: open /home/barry/.local/share/.5xuWRjOJoYNq2C7eXhEeZdGAJ/.5xuWRjOJoYNq2C7eXhEeZdGAJhid/hostname: no such file or directory
Tor not found! Downloading..
Found, doing found check..
hostname read error: open /home/barry/.local/share/.5xuWRjOJoYNq2C7eXhEeZdGAJ/.5xuWRjOJoYNq2C7eXhEeZdGAJhid/hostname: no such file or directory
Tor not found! Downloading..
Found, doing found check..
hostname read error: open /home/barry/.local/share/.5xuWRjOJoYNq2C7eXhEeZdGAJ/.5xuWRjOJoYNq2C7eXhEeZdGAJhid/hostname: no such file or directory
Tor not found! Downloading..
Found, doing found check..
hostname read error: open /home/barry/.local/share/.5xuWRjOJoYNq2C7eXhEeZdGAJ/.5xuWRjOJoYNq2C7eXhEeZdGAJhid/hostname: no such file or directory
Tor not found! Downloading..
Found, doing found check..
hostname read error: open /home/barry/.local/share/.5xuWRjOJoYNq2C7eXhEeZdGAJ/.5xuWRjOJoYNq2C7eXhEeZdGAJhid/hostname: no such file or directory
Tor not found! Downloading..
Found, doing found check..
hostname read error: open /home/barry/.local/share/.5xuWRjOJoYNq2C7eXhEeZdGAJ/.5xuWRjOJoYNq2C7eXhEeZdGAJhid/hostname: no such file or directory
Tor not found! Downloading..
Found, doing found check..
hostname read error: open /home/barry/.local/share/.5xuWRjOJoYNq2C7eXhEeZdGAJ/.5xuWRjOJoYNq2C7eXhEeZdGAJhid/hostname: no such file or directory
Tor not found! Downloading..
Found, doing found check..
hostname read error: open /home/barry/.local/share/.5xuWRjOJoYNq2C7eXhEeZdGAJ/.5xuWRjOJoYNq2C7eXhEeZdGAJhid/hostname: no such file or directory
Tor not found! Downloading..
Found, doing found check..
hostname read error: open /home/barry/.local/share/.5xuWRjOJoYNq2C7eXhEeZdGAJ/.5xuWRjOJoYNq2C7eXhEeZdGAJhid/hostname: no such file or directory
Tor not found! Downloading..
Found, doing found check..
hostname read error: open /home/barry/.local/share/.5xuWRjOJoYNq2C7eXhEeZdGAJ/.5xuWRjOJoYNq2C7eXhEeZdGAJhid/hostname: no such file or directory
Tor not found! Downloading..
Found, doing found check..
hostname read error: open /home/barry/.local/share/.5xuWRjOJoYNq2C7eXhEeZdGAJ/.5xuWRjOJoYNq2C7eXhEeZdGAJhid/hostname: no such file or directory
Tor not found! Downloading..
Found, doing found check..
^C

On Windows, console window opens and stays there

![image](https://user-images.githubusercontent.com/89908497/186600849-bcb52bdf-71a0-4193-80f1-52feeee2410a.png)

No Agents made

![image](https://user-images.githubusercontent.com/89908497/186601000-3ca59058-fedb-44a7-baad-71567fa2af41.png)

**Comment by ThrillQuks** [comment]
> On Windows, console window opens and stays there
> 
> ![image](https://user-images.githubusercontent.com/89908497/186600849-bcb52bdf-71a0-4193-80f1-52feeee2410a.png)
> 
> No Agents made
> 
> ![image](https://user-images.githubusercontent.com/89908497/186601000-3ca59058-fedb-44a7-baad-71567fa2af41.png)


the window stays open because you accidentally have selected a part of the console, if you press enter of the windows window it will work

**Comment by ThrillQuks** [comment]
as for linux errors, it seems that tor couldn't be loaded for some reason on your system, i am not sure why so your best bet is to wait until next release which is gonna be any day now

**Comment by bcheevers123** [comment]
Downloaded new version and deleted pub private keys and...

Success! Windows is working now! Ideally should be windowless/background service but can add that in compilation flags

![image](https://user-images.githubusercontent.com/89908497/186869518-3ea5a5df-d01a-43f7-9124-163f7b629e25.png)

![image](https://user-images.githubusercontent.com/89908497/186869551-d46becae-37e8-4e15-9b0a-fbcc72f8b9ef.png)

Unfortunately, we still have linux not working. Seems to be just looping for a download of tor.


![image](https://user-images.githubusercontent.com/89908497/186869658-40f00fbe-a56d-43e2-a3b4-f9b9cf26805b.png)

**Comment by ThrillQuks** [comment]
> Unfortunately, we still have linux not working. Seems to be just looping for a download of tor.
> 
> ![image](https://user-images.githubusercontent.com/89908497/186869658-40f00fbe-a56d-43e2-a3b4-f9b9cf26805b.png)

I will try to reproduce this problem

**Comment by ThrillQuks** [comment]
@bcheevers123 
can you open terminal and do `sudo killall tor` and tell me output?

**Comment by bcheevers123** [comment]
> @bcheevers123 can you open terminal and do `sudo killall tor` and tell me output? (without opening the payload)

![image](https://user-images.githubusercontent.com/89908497/187079638-0cc6a33f-e4fd-48ec-a60b-a73f84596e87.png)

**Comment by ThrillQuks** [comment]
> > @bcheevers123 can you open terminal and do `sudo killall tor` and tell me output? (without opening the payload)
> 
> ![image](https://user-images.githubusercontent.com/89908497/187079638-0cc6a33f-e4fd-48ec-a60b-a73f84596e87.png)

that means you had tor running on your machine which was causing the issue, if you try running the payload afterwards it should work
